server:
  port: 50080
  proxy:
    - prefix: "/editor/"
      target: "http://localhost:50081/"
    - prefix: "/src/"
      target: "http://localhost:50081/"
    - prefix: "/@vite/"
      target: "http://localhost:50081/"
    - prefix: "/@fs/"
      target: "http://localhost:50081/"
    - prefix: "/node_modules/"
      target: "http://localhost:50081/"
    - prefix: "/runtime/"
      target: "http://localhost:50082/"
